# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=40)),
                ('year', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='photo')),
                ('address', models.CharField(max_length=200)),
                ('father', models.CharField(max_length=255)),
                ('mother', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cgpa', models.FloatField()),
                ('birth_day', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('nationality', models.CharField(max_length=25)),
                ('phone_no', models.CharField(blank=True, max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_skills', models.CharField(blank=True, help_text='Sparate languages by comma', max_length=200)),
                ('other_skills', models.CharField(blank=True, help_text='Sparate Skills by comma', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=20)),
                ('joining_year', models.DateField(blank=True, null=True)),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
